In [5]:
#!pip install kagglehub

In [6]:
import kagglehub
from pathlib import Path
from tqdm import tqdm
import pandas as pd

In [10]:
path = kagglehub.dataset_download("waqi786/most-used-beauty-cosmetics-products-in-the-world")

print("Path to dataset files:", path)

Path to dataset files: /Users/hanane/.cache/kagglehub/datasets/waqi786/most-used-beauty-cosmetics-products-in-the-world/versions/1

In [ ]:
# world dataset for Valeria
dataset_dir = Path("/Users/valeriaacevedo/.cache/kagglehub/datasets/waqi786/most-used-beauty-cosmetics-products-in-the-world/versions/1")
csv_path_world = next(dataset_dir.glob("*.csv"))

In [13]:
# world dataset for Hanane
dataset_dir = Path("/Users/hanane/.cache/kagglehub/datasets/waqi786/most-used-beauty-cosmetics-products-in-the-world/versions/1")
csv_path_world = next(dataset_dir.glob("*.csv"))

In [14]:
df_world = pd.read_csv(csv_path_world)
df_world.head(5)

,Product_Name,Brand,Category,Usage_Frequency,Price_USD,Rating,Number_of_Reviews,Product_Size,Skin_Type,Gender_Target,Packaging_Type,Main_Ingredient,Cruelty_Free,Country_of_Origin
0,Ultra Face Mask,Drunk Elephant,Blush,Weekly,67.85,1.4,686,30ml,Sensitive,Female,Tube,Retinol,False,Australia
1,Ultra Lipstick,Laura Mercier,Makeup Remover,Occasional,116.43,4.2,5483,250ml,Dry,Unisex,Bottle,Shea Butter,False,UK
2,Ultra Serum,Natasha Denona,Highlighter,Daily,90.84,1.6,5039,100ml,Sensitive,Male,Compact,Aloe Vera,True,Italy
3,Divine Serum,Ilia Beauty,Face Mask,Occasional,55.17,3.2,6202,250ml,Normal,Male,Tube,Glycerin,True,South Korea
4,Super Foundation,Charlotte Tilbury,Highlighter,Occasional,140.56,1.7,297,100ml,Oily,Female,Compact,Glycerin,False,Germany

In [15]:
df_world.shape

(15000, 14)

In [16]:
df_world.columns

Index(['Product_Name', 'Brand', 'Category', 'Usage_Frequency', 'Price_USD',
       'Rating', 'Number_of_Reviews', 'Product_Size', 'Skin_Type',
       'Gender_Target', 'Packaging_Type', 'Main_Ingredient', 'Cruelty_Free',
       'Country_of_Origin'],
      dtype='object')

In [17]:
df_world.describe

<bound method NDFrame.describe of            Product_Name              Brand        Category Usage_Frequency  \
0       Ultra Face Mask     Drunk Elephant           Blush          Weekly
1        Ultra Lipstick      Laura Mercier  Makeup Remover      Occasional
2           Ultra Serum     Natasha Denona     Highlighter           Daily
3          Divine Serum        Ilia Beauty       Face Mask      Occasional
4      Super Foundation  Charlotte Tilbury     Highlighter      Occasional
...                 ...                ...             ...             ...
14995    Magic Eyeliner         Patrick Ta       Face Mask           Daily
14996    Perfect Powder            Farsali           Serum          Weekly
14997       Magic Serum            Kiehl’s     Highlighter      Occasional
14998     Magic Mascara       Perricone MD          Powder          Weekly
14999  Divine Lip Liner             Tatcha           Blush           Daily

       Price_USD  Rating  Number_of_Reviews Product_Size    Skin_Type  \
0          67.85     1.4                686         30ml    Sensitive
1         116.43     4.2               5483        250ml          Dry
2          90.84     1.6               5039        100ml    Sensitive
3          55.17     3.2               6202        250ml       Normal
4         140.56     1.7                297        100ml         Oily
...          ...     ...                ...          ...          ...
14995     131.64     2.8               1470        250ml    Sensitive
14996      76.35     2.1               7652        250ml          Dry
14997      65.37     4.2                811         30ml  Combination
14998      59.93     4.8               5482        250ml          Dry
14999      36.96     1.1               5452        200ml       Normal

      Gender_Target Packaging_Type Main_Ingredient  Cruelty_Free  \
0            Female           Tube         Retinol         False
1            Unisex         Bottle     Shea Butter         False
2              Male        Compact       Aloe Vera          True
3              Male           Tube        Glycerin          True
4            Female        Compact        Glycerin         False
...             ...            ...             ...           ...
14995        Unisex           Tube       Aloe Vera          True
14996        Unisex            Jar  Salicylic Acid          True
14997        Unisex            Jar     Shea Butter         False
14998          Male            Jar       Aloe Vera          True
14999        Female         Bottle     Shea Butter         False

      Country_of_Origin
0             Australia
1                    UK
2                 Italy
3           South Korea
4               Germany
...                 ...
14995             Italy
14996               USA
14997       South Korea
14998               USA
14999                UK

[15000 rows x 14 columns]>

In [18]:
df_world.isnull().sum()

Product_Name         0
Brand                0
Category             0
Usage_Frequency      0
Price_USD            0
Rating               0
Number_of_Reviews    0
Product_Size         0
Skin_Type            0
Gender_Target        0
Packaging_Type       0
Main_Ingredient      0
Cruelty_Free         0
Country_of_Origin    0
dtype: int64

In [19]:
df_world.duplicated().sum()

np.int64(0)

In [20]:
df_world = df_world.drop_duplicates()

In [21]:
columns_to_drop = [
'Brand' ,
'Category' , 
'Usage_Frequency' , 
'Product_Size' , 
'Skin_Type', 
'Packaging_Type' , 
'Main_Ingredient',

]
df_world= df_world.drop(columns=columns_to_drop, errors='ignore')

In [22]:
df_world.dtypes

Product_Name          object
Price_USD            float64
Rating               float64
Number_of_Reviews      int64
Gender_Target         object
Cruelty_Free            bool
Country_of_Origin     object
dtype: object

In [23]:
df_world.shape

(15000, 7)

In [24]:
df_world.columns =(
   df_world.columns
    .str.lower()

)

In [25]:
df_world.nunique()

product_name          120
price_usd            9204
rating                 41
number_of_reviews    7734
gender_target           3
cruelty_free            2
country_of_origin       8
dtype: int64

In [26]:
df_world.describe

<bound method NDFrame.describe of            product_name  price_usd  rating  number_of_reviews gender_target  \
0       Ultra Face Mask      67.85     1.4                686        Female
1        Ultra Lipstick     116.43     4.2               5483        Unisex
2           Ultra Serum      90.84     1.6               5039          Male
3          Divine Serum      55.17     3.2               6202          Male
4      Super Foundation     140.56     1.7                297        Female
...                 ...        ...     ...                ...           ...
14995    Magic Eyeliner     131.64     2.8               1470        Unisex
14996    Perfect Powder      76.35     2.1               7652        Unisex
14997       Magic Serum      65.37     4.2                811        Unisex
14998     Magic Mascara      59.93     4.8               5482          Male
14999  Divine Lip Liner      36.96     1.1               5452        Female

       cruelty_free country_of_origin
0             False         Australia
1             False                UK
2              True             Italy
3              True       South Korea
4             False           Germany
...             ...               ...
14995          True             Italy
14996          True               USA
14997         False       South Korea
14998          True               USA
14999         False                UK

[15000 rows x 7 columns]>

In [27]:
df_world.describe()

          price_usd        rating  number_of_reviews
count  15000.000000  15000.000000       15000.000000
mean      80.134108      3.002327        5014.231333
std       40.402983      1.168029        2855.665464
min       10.000000      1.000000          52.000000
25%       45.480000      2.000000        2562.000000
50%       80.040000      3.000000        5002.000000
75%      114.760000      4.000000        7497.000000
max      149.990000      5.000000       10000.000000

In [28]:
# Product more expensive

In [29]:
top_precios = df_world.sort_values(by='price_usd', ascending=False).head(10)
print(top_precios[['price_usd', 'product_name', 'gender_target']])

       price_usd       product_name gender_target
11484     149.99     Ultra Eyeliner        Unisex
5958      149.98      Magic Mascara        Unisex
10363     149.97   Perfect CC Cream        Unisex
12667     149.97  Perfect Lip Liner          Male
8874      149.93   Divine Lip Gloss        Unisex
7551      149.93        Magic Blush          Male
924       149.92  Perfect Lip Liner          Male
6138      149.92   Super Eye Shadow        Female
1263      149.92    Ultra Lip Gloss          Male
11197     149.91   Perfect Eyeliner          Male

In [30]:
top_rating = df_world.sort_values(by='number_of_reviews', ascending=False).head(10)
print(top_precios[['product_name', 'number_of_reviews']])

            product_name  number_of_reviews
11484     Ultra Eyeliner               1770
5958       Magic Mascara               8703
10363   Perfect CC Cream               7806
12667  Perfect Lip Liner               2239
8874    Divine Lip Gloss               5123
7551         Magic Blush               6228
924    Perfect Lip Liner               2040
6138    Super Eye Shadow               6539
1263     Ultra Lip Gloss               3714
11197   Perfect Eyeliner               9177

In [31]:
top_rating = df_world.sort_values(by='number_of_reviews', ascending=False).head(10)
print(top_precios[['product_name', 'number_of_reviews','cruelty_free' ]])

            product_name  number_of_reviews  cruelty_free
11484     Ultra Eyeliner               1770          True
5958       Magic Mascara               8703          True
10363   Perfect CC Cream               7806         False
12667  Perfect Lip Liner               2239         False
8874    Divine Lip Gloss               5123         False
7551         Magic Blush               6228          True
924    Perfect Lip Liner               2040          True
6138    Super Eye Shadow               6539          True
1263     Ultra Lip Gloss               3714          True
11197   Perfect Eyeliner               9177          True

In [32]:
EU_COUNTRIES = {
    "Austria", "Belgium", "Bulgaria", "Croatia", "Cyprus",
    "Czech Republic", "Denmark", "Estonia", "Finland", "France",
    "Germany", "Greece", "Hungary", "Ireland", "Italy", "Latvia",
    "Lithuania", "Luxembourg", "Malta", "Netherlands", "Poland",
    "Portugal", "Romania", "Slovakia", "Slovenia", "Spain", "Sweden"
}

In [33]:
countries   = sorted(df_world["country_of_origin"].unique())
dim_country = pd.DataFrame({
    "country_id"  : range(1, len(countries) + 1),
    "country_name": countries,
    "is_eu"       : [1 if c in EU_COUNTRIES else 0 for c in countries]
})

In [34]:
country_map = dict(zip(dim_country["country_name"], dim_country["country_id"]))

In [35]:
df_world["country_id"] = df_world["country_of_origin"].map(country_map)

In [38]:
print("dim_country_id:")
dim_country.to_csv("dim_country_id.csv", index=False)

dim_country_id:

In [39]:

all_genders = sorted(
    set(df_world["gender_target"].unique()) 
)

dim_gender = pd.DataFrame({
    "gender_id"   : range(1, len(all_genders) + 1),
    "gender_label": all_genders
})

In [40]:
print("dim_gender:")
print(dim_gender)
dim_gender.to_csv("dim_gender.csv", index=False)

dim_gender:
   gender_id gender_label
0          1       Female
1          2         Male
2          3       Unisex

In [41]:
gender_map = dict(zip(dim_gender["gender_label"], dim_gender["gender_id"]))

In [42]:
df_world["gender_id"]  = df_world["gender_target"].map(gender_map)

In [43]:
beauty_products = df_world[[
    "product_name",
    "price_usd",
    "rating",
    "number_of_reviews",
    "gender_id",
    "cruelty_free",
    "country_id"
]]

In [ ]:
df_world.to_csv('world_clean.csv', index=False)